name: Build and Deploy

on:
  repository_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      NOTION_CACHE: true
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DBID: ${{ secrets.NOTION_DBID }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run builds and deploys with ${{ matrix.node-version }}
      run: |
        yarn install && yarn build && yarn export

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    env:
      NOTION_CACHE: true
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DBID: ${{ secrets.NOTION_DBID }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Run next export
      run: |
        yarn install && yarn build && yarn export
    - name: deploy by scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "out/*"
        target: "web"
        strip_components: 1

